### PR TITLE
TTTBeginRound: Print Roles in Console

### PR DESCRIPTION
**Pull request by simonkolloch**
Moinsen

### CODE REVIEW

**Comment by Zumoari** [comment]
ok cool

**Comment by simonkolloch** [comment]
Please Merge, because urgend fxes ASAP. Thank Y

**Comment by simonkolloch** [comment]
FUCK wrong Repo. I am sorry for what i did in my life the last minutes

**Comment by Henotu** [comment]
I guess I can close this then

**Pull request closed without merging**
